name: Terraform-Format-Check-CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  check:
    name: check terraform fmt job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform-fmt
        uses: dflook/terraform-fmt@v1.29.1
        id: fmt-check

      - name: Wrong formatting found
        if: ${{ failure() && steps.fmt-check.outputs.failure-reason == 'check-failed' }}
        run: echo "Terraform formatting check failed."
